import NavbarUnauthed from "../components/layout/NavbarUnauthed";
import NavbarAuthed from "../components/layout/NavbarAuthed";
import { getUser } from "@/app/lib/dal";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default async function RootLayout({ children }) {
  const user = await getUser();

  // const userRole = session.role // Assuming 'role' is part of the session object
 
  // else {
  //   redirect('/login')
  // }
  return (
    <html lang="en">
      <body>
        {user ? <NavbarAuthed /> : <NavbarUnauthed />}
        {children}
      </body>
    </html>
  );
  
}
